### ISSUE TITLE
byte-blob generated by byte-blob-drop does not correctly convert to blob with byte-blob->blob

### ISSUE THREAD

**Issue by dthedens** [iraikov/chicken-byte-blob#1]
`byte-blob-drop` works fine when the result is another byte-blob.

    > (byte-blob->list (byte-blob-drop (list->byte-blob '(1 2 3 4)) 2))
    (3 4)

However, when the result is converted to a `blob`, the effect of `byte-blob-drop` is lost since there is an offset in the new `byte-blob` which does not carry over when converted to a `blob`. 

    ;; Should be #${0304}
    > (byte-blob->blob (byte-blob-drop (list->byte-blob '(1 2 3 4)) 2))
    #${01020304}

The `blob` is correctly created when using `byte-blob-take`, 

    > (byte-blob->blob (byte-blob-take (list->byte-blob '(1 2 3 4)) 2))
    #${0102}
and also with `byte-blob-span`.

    > (byte-blob->blob (byte-blob-span (list->byte-blob '(1 2 3 4)) 2 4))
    #${0304}

It appears that the way the resulting `byte-blob` is created is different for `byte-blob-take` and `byte-blob-drop` such that this type of issue does not affect `byte-blob-take`. 

This is using 

    CHICKEN
    (c) 2008-2020, The CHICKEN Team
    (c) 2000-2007, Felix L. Winkelmann
    Version 5.2.0 (rev 317468e4)
    linux-unix-gnu-x86-64 [ 64bit dload ptables ]

**Comment by iraikov** [comment]
Thanks for reporting this and for the patch. I have created a new release that includes the fix.

**Comment by dthedens** [comment]
Thank you for the quick turnaround.
